<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PruebaTecnicaModel\PruebaTecnicaModel.csproj" />
    <ProjectReference Include="..\PruebaTecnicaShared\PruebaTecnicaShared.csproj" />
  </ItemGroup>

</Project>
